changelog:
  exclude:
    labels: [dependencies]
  categories:
    - title: Breaking Changes
      labels: [breaking]
    - title: New Features
      labels: [feature]
    - title: Bug Fixes
      labels: [bug]
    - title: Enhancements
      labels: [enhancement]
