name: Dependencies
on:
  push:
    branches-ignore: [master]
    paths:
      - package.json
      - yarn.lock
      - .yarn/cache/*
concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn --immutable --immutable-cache --check-cache
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          base-ref: master
          head-ref: ${{ github.ref }}
  usage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn --immutable --immutable-cache
      - run: yarn depcheck
