name: Dependencies
on:
  push:
    branches-ignore: [master]
    paths:
      - "!package.json"
      - "!yarn.lock"
      - "!.yarn/cache/*"
concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'skipped'
  review:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'skipped'
