name: Publish
on:
  push:
    tags: [v*.*.*]
env:
  OPENRCT2_DIR: OpenRCT2
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v3
        id: npm
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: softprops/action-gh-release@v2
        if: steps.npm.outputs.type != 'none'
        with:
          files: dist/benchwarmer.js
          generate_release_notes: true
