name: Publish
on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "*.*.x"
env:
  OPENRCT2_DIR: OpenRCT2
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build Plugin
        run: yarn build
      - name: Publish to NPM
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
