name: Publish
on:
  push:
    branches: [master]
env:
  OPENRCT2_DIR: OpenRCT2
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        id: npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: softprops/action-gh-release@v1
        if: steps.npm.outputs.type != 'none'
        with:
          files: dist/benchwarmer.js
          generate_release_notes: true
