name: Tag
on:
  push:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - name: Run yarn version apply
        run: |
          current=v$(jq -r '.version' package.json)
          yarn version apply
          version=v$(jq -r '.version' package.json)

          if [[ $current != $version ]]; then
            git add package.json
            git commit -am "release $version"
            git tag "$version" -m "release $version"
            git push --follow-tags
          fi
