name: Tag
on:
  push:
    branches: [master]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v1
      - run: |
          yarn version apply
          git add package.json
          git commit -am "release v$(jq '.version' package.json)"
          git tag "v$(version)" -m "release v$(jq '.version' package.json)"
          git push --follow-tags
