name: Version
on:
  pull_request:
    types: [labeled]
jobs:
  major:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels.*.name == 'breaking'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          yarn version major --deferred 
          git add .yarn/versions
          git commit -am "release new minor version"
          git push
  minor:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels.*.name == 'feature'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          yarn version minor --deferred 
          git add .yarn/versions
          git commit -am "release new minor version"
          git push
  patch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels.*.name == 'bug' || github.event.pull_request.labels.*.name == 'enhancement'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          yarn version patch --deferred 
          git add .yarn/versions
          git commit -am "release new minor version"
          git push
